src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;
use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ApiResource]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $Prix = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Taille = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image2 = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->Taille;
    }

    public function setTaille(string $Taille): self
    {
        $this->Taille = $Taille;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Articlefemme;
use App\Repository\ArticleRepository;
use App\Repository\ArticlefemmeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class ArticleController extends AbstractController
{
    #[Route('/articles', name: 'app_article')]
    public function show(Request $request, Environment $twig, ArticleRepository $articleRepository): Response
    {

        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $articleRepository->getArticlePaginator($offset);

        return new Response($twig->render('products.html.twig', [
                        'articles' => $paginator,
            'previous' => $offset - articleRepository::PAGINATOR_PER_PAGE,
            'next' => min(count($paginator), $offset + articleRepository::PAGINATOR_PER_PAGE),
                    ]));                    
    }

    
    #[Route('/article/{id}', name: 'article')]
    public function details(Environment $twig, Article $article): Response
    {
        return new Response($twig->render('single_product.html.twig', [
            'article' => $article
        ]));
    }
    
    // #[Route('/articlefemmes', name: 'app_article')]
    // public function show(Request $request, Environment $twig, ArticlefemmeRepository $articleRepository): Response
    // {

    //     $offset = max(0, $request->query->getInt('offset', 0));
    //     $paginator = $articlefemmeRepository->getArticlefemmePaginator($offset);

    //     return new Response($twig->render('products.html.twig', [
    //                     'articlefemmes' => $paginator,
    //         'previous' => $offset - articleRepository::PAGINATOR_PER_PAGE,
    //         'next' => min(count($paginator), $offset + articleRepository::PAGINATOR_PER_PAGE),
    //                 ]));                    
    // }

}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/symfo/src/Controller/ArticleController.php'|file_link(0) }}">src/Controller/ArticleController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/symfo/templates/article/index.html.twig'|file_link(0) }}">templates/article/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/article/product.html.twig
<div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{{ path('article',{id: article.id}) }}"><i class="fa fa-eye"></i></a></li>
                                </ul>
                            </div>
                            <img src="{{ asset('/image/'~(article.Image )) }}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>{{article.nom}}</h4>
                            <span>{{article.prix}}€</span>
                            <span>{{article.description}}</span>
                        </div>
                    </div>
                </div>
                

templates/article/product_femme.twig
<div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{{ path('article',{id: article.id}) }}"><i class="fa fa-eye"></i></a></li>
                                </ul>
                            </div>
                            <img src="{{ asset('/image/'~(article.Image )) }}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>{{article.nom}}</h4>
                            <span>{{article.prix}}€</span>
                            <span>{{article.description}}</span>
                        </div>
                    </div>
                </div>
                